# Generated by Django 3.1.7 on 2021-02-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='amount_cash',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='amount_crypto',
            field=models.DecimalField(decimal_places=20, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='date_of_transfer',
            field=models.DateTimeField(null=True),
        ),
    ]
