# Generated by Django 3.1.7 on 2021-03-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_transaction_current_value_of_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='current_value_of_asset',
        ),
    ]
